2025-06-27 14:14:57,936 - __main__ - CRITICAL - Fatal error: No module named 'config'
Traceback (most recent call last):
  File "c:\moy python\projects vs code\roma\user_app\main.py", line 67, in main
    from config import validate_config, CREDENTIALS_FILE
ModuleNotFoundError: No module named 'config'
2025-06-27 14:15:24,237 - __main__ - CRITICAL - Fatal error: No module named 'config'
Traceback (most recent call last):
  File "c:\moy python\projects vs code\roma\user_app\main.py", line 67, in main
    from config import validate_config, CREDENTIALS_FILE
ModuleNotFoundError: No module named 'config'
2025-06-27 14:15:43,512 - __main__ - CRITICAL - Fatal error: No module named 'config'
Traceback (most recent call last):
  File "c:\moy python\projects vs code\roma\user_app\main.py", line 67, in main
    from config import validate_config, CREDENTIALS_FILE
ModuleNotFoundError: No module named 'config'
2025-06-27 15:14:07,191 - __main__ - INFO - Запуск приложения
2025-06-27 15:14:29,680 - __main__ - INFO - Успешный вход: 1@ya.ru
2025-06-27 15:14:32,016 - __main__ - INFO - Успешный вход: 1@ya.ru
2025-06-27 15:17:59,172 - __main__ - INFO - Запуск приложения
2025-06-27 15:23:33,417 - __main__ - INFO - Запуск приложения
2025-06-27 15:23:53,080 - __main__ - INFO - Успешный вход: 1@ya.ru
2025-06-27 15:23:56,449 - __main__ - INFO - Успешный вход: 1@ya.ru
2025-06-27 15:27:30,888 - __main__ - INFO - Запуск приложения
2025-06-27 15:27:50,333 - __main__ - INFO - Успешный вход: 1@ya.ru
2025-06-27 15:27:53,436 - __main__ - INFO - Успешный вход: 1@ya.ru
2025-06-27 15:29:48,840 - __main__ - INFO - Запуск приложения
2025-06-27 15:30:09,713 - __main__ - INFO - Успешный вход: 2@ya.ru
2025-06-27 15:30:13,060 - __main__ - INFO - Успешный вход: 2@ya.ru
2025-06-27 15:33:09,798 - __main__ - INFO - Запуск приложения
2025-06-27 15:33:28,169 - __main__ - INFO - Успешный вход: 1@ya.ru
2025-06-27 15:36:42,827 - __main__ - INFO - Запуск приложения
2025-06-27 15:37:22,301 - __main__ - INFO - Успешный вход: 3@ya.ru
2025-06-27 15:45:46,304 - __main__ - INFO - Запуск приложения
2025-06-27 15:46:08,773 - __main__ - INFO - Успешный вход: 2@ya.ru
2025-06-27 16:15:07,511 - user_app.db_local - WARNING - Не удалось сразу синхронизировать запись: 'SheetsAPI' object has no attribute 'log_action'
2025-06-27 16:15:07,513 - user_app.gui - INFO - Смена завершена: 2@ya.ru. Причина: Завершение смены (нормальное)
2025-07-01 16:12:52,047 - __main__ - INFO - Запуск приложения
2025-07-01 16:45:35,610 - __main__ - INFO - Запуск приложения
2025-07-01 16:45:55,972 - __main__ - INFO - Успешный вход: 1@ya.ru
2025-07-01 17:01:56,140 - __main__ - INFO - Запуск приложения
2025-07-01 17:02:15,038 - __main__ - INFO - Успешный вход: 3@ya.ru
2025-07-01 17:19:42,335 - user_app.db_local - WARNING - Не удалось сразу синхронизировать запись: name 'sheets_api' is not defined
2025-07-01 17:19:42,340 - user_app.gui - INFO - Смена завершена: 3@ya.ru. Причина: Завершение смены (нормальное)
2025-07-01 17:43:54,014 - __main__ - INFO - Запуск приложения
2025-07-01 17:44:14,234 - __main__ - INFO - Успешный вход: 3@ya.ru
2025-07-02 08:52:14,803 - user_app.db_local - WARNING - Не удалось сразу синхронизировать запись: name 'sheets_api' is not defined
2025-07-02 08:52:14,805 - user_app.gui - INFO - Смена завершена: 3@ya.ru. Причина: Приложение закрыто через крестик
2025-07-02 08:52:14,806 - __main__ - INFO - Приложение закрыто пользователем: 3@ya.ru
2025-07-02 09:28:01,064 - __main__ - INFO - Запуск приложения
2025-07-02 09:28:40,826 - __main__ - INFO - Запуск приложения
2025-07-02 09:36:33,652 - __main__ - INFO - Запуск приложения
2025-07-02 09:37:04,495 - __main__ - INFO - Успешный вход: 1@ya.ru
2025-07-02 09:46:10,180 - user_app.db_local - WARNING - Не удалось сразу синхронизировать запись: name 'sheets_api' is not defined
2025-07-02 09:46:10,182 - user_app.gui - INFO - Смена завершена: 1@ya.ru. Причина: Приложение закрыто через крестик
2025-07-02 09:46:10,184 - __main__ - INFO - Приложение закрыто пользователем: 1@ya.ru
2025-07-02 09:57:17,014 - __main__ - INFO - Запуск приложения
2025-07-02 09:57:43,757 - __main__ - INFO - Успешный вход: 3@ya.ru
2025-07-02 09:58:11,072 - user_app.db_local - WARNING - Не удалось сразу синхронизировать запись: name 'sheets_api' is not defined
2025-07-02 09:58:11,074 - user_app.gui - INFO - Смена завершена: 3@ya.ru. Причина: Завершение смены (нормальное)
2025-07-02 10:05:05,627 - __main__ - INFO - Запуск приложения
2025-07-02 10:05:27,257 - __main__ - INFO - Успешный вход: 3@ya.ru
2025-07-02 10:05:27,275 - __main__ - ERROR - Ошибка при создании главного окна: 'LocalDB' object has no attribute '_clean_old_data'
2025-07-02 10:14:19,979 - __main__ - INFO - Запуск приложения
2025-07-02 10:14:35,662 - __main__ - INFO - Успешный вход: 3@ya.ru
2025-07-02 10:14:54,786 - user_app.db_local - WARNING - Не удалось сразу синхронизировать запись: name 'sheets_api' is not defined
2025-07-02 10:14:54,792 - user_app.gui - INFO - Смена завершена: 3@ya.ru. Причина: Завершение смены (нормальное)
2025-07-03 13:09:29,033 - __main__ - INFO - Запуск приложения
2025-07-03 13:09:49,589 - __main__ - INFO - Успешный вход: 3@ya.ru
2025-07-03 13:09:59,840 - user_app.db_local - WARNING - Не удалось сразу синхронизировать запись: name 'sheets_api' is not defined
2025-07-03 13:09:59,841 - user_app.gui - INFO - Смена завершена: 3@ya.ru. Причина: Завершение смены (нормальное)
